/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * User API
 * User API
 * OpenAPI spec version: 1.0.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { useQuery } from '@tanstack/react-query';

import { customFetch } from './custom-fetch';
export type SayHelloUser200 = {
  message: string;
};

export type HealthCheck200 = {
  message: string;
};

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Says hello in multiple languages
 */
export const getSayHelloUserUrl = (languageCode: 'en' | 'fr' | 'es' | 'ge') => {
  return `http://localhost:3002/hello-user/${languageCode}`;
};

export const sayHelloUser = async (
  languageCode: 'en' | 'fr' | 'es' | 'ge',
  options?: RequestInit
): Promise<SayHelloUser200> => {
  return customFetch<SayHelloUser200>(getSayHelloUserUrl(languageCode), {
    ...options,
    method: 'GET',
  });
};

export const getSayHelloUserQueryKey = (
  languageCode: 'en' | 'fr' | 'es' | 'ge'
) => {
  return [`http://localhost:3002/hello-user/${languageCode}`] as const;
};

export const getSayHelloUserQueryOptions = <
  TData = Awaited<ReturnType<typeof sayHelloUser>>,
  TError = unknown,
>(
  languageCode: 'en' | 'fr' | 'es' | 'ge',
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sayHelloUser>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSayHelloUserQueryKey(languageCode);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof sayHelloUser>>> = ({
    signal,
  }) => sayHelloUser(languageCode, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!languageCode,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof sayHelloUser>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SayHelloUserQueryResult = NonNullable<
  Awaited<ReturnType<typeof sayHelloUser>>
>;
export type SayHelloUserQueryError = unknown;

export function useSayHelloUser<
  TData = Awaited<ReturnType<typeof sayHelloUser>>,
  TError = unknown,
>(
  languageCode: 'en' | 'fr' | 'es' | 'ge',
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sayHelloUser>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof sayHelloUser>>,
          TError,
          Awaited<ReturnType<typeof sayHelloUser>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSayHelloUser<
  TData = Awaited<ReturnType<typeof sayHelloUser>>,
  TError = unknown,
>(
  languageCode: 'en' | 'fr' | 'es' | 'ge',
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sayHelloUser>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof sayHelloUser>>,
          TError,
          Awaited<ReturnType<typeof sayHelloUser>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSayHelloUser<
  TData = Awaited<ReturnType<typeof sayHelloUser>>,
  TError = unknown,
>(
  languageCode: 'en' | 'fr' | 'es' | 'ge',
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sayHelloUser>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useSayHelloUser<
  TData = Awaited<ReturnType<typeof sayHelloUser>>,
  TError = unknown,
>(
  languageCode: 'en' | 'fr' | 'es' | 'ge',
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sayHelloUser>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSayHelloUserQueryOptions(languageCode, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Health check
 */
export const getHealthCheckUrl = () => {
  return 'http://localhost:3002/health';
};

export const healthCheck = async (
  options?: RequestInit
): Promise<HealthCheck200> => {
  return customFetch<HealthCheck200>(getHealthCheckUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getHealthCheckQueryKey = () => {
  return ['http://localhost:3002/health'] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = unknown;

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthCheck>>,
          TError,
          Awaited<ReturnType<typeof healthCheck>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthCheck>>,
          TError,
          Awaited<ReturnType<typeof healthCheck>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
