/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * User Service API
 * User Service API
 * OpenAPI spec version: 1.0.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { useQuery } from '@tanstack/react-query';

export type SayHelloParams = {
  /**
   * @minLength 1
   */
  name: string;
};

export type SayHello200 = {
  message: string;
};

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/**
 * Says hello in 3 languages
 */
export type sayHelloResponse200 = {
  data: SayHello200;
  status: 200;
};

export type sayHelloResponseComposite = sayHelloResponse200;

export type sayHelloResponse = sayHelloResponseComposite & {
  headers: Headers;
};

export const getSayHelloUrl = (
  languageCode: 'en' | 'fr' | 'es' | 'ge',
  params: SayHelloParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `http://localhost:3000/hello/${languageCode}?${stringifiedParams}`
    : `http://localhost:3000/hello/${languageCode}`;
};

export const sayHello = async (
  languageCode: 'en' | 'fr' | 'es' | 'ge',
  params: SayHelloParams,
  options?: RequestInit
): Promise<sayHelloResponse> => {
  const res = await fetch(getSayHelloUrl(languageCode, params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: sayHelloResponse['data'] = body ? JSON.parse(body) : {};

  return { data, status: res.status, headers: res.headers } as sayHelloResponse;
};

export const getSayHelloQueryKey = (
  languageCode: 'en' | 'fr' | 'es' | 'ge',
  params: SayHelloParams
) => {
  return [
    `http://localhost:3000/hello/${languageCode}`,
    ...(params ? [params] : []),
  ] as const;
};

export const getSayHelloQueryOptions = <
  TData = Awaited<ReturnType<typeof sayHello>>,
  TError = unknown,
>(
  languageCode: 'en' | 'fr' | 'es' | 'ge',
  params: SayHelloParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sayHello>>, TError, TData>
    >;
    fetch?: RequestInit;
  }
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSayHelloQueryKey(languageCode, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof sayHello>>> = ({
    signal,
  }) => sayHello(languageCode, params, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!languageCode,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof sayHello>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type SayHelloQueryResult = NonNullable<
  Awaited<ReturnType<typeof sayHello>>
>;
export type SayHelloQueryError = unknown;

export function useSayHello<
  TData = Awaited<ReturnType<typeof sayHello>>,
  TError = unknown,
>(
  languageCode: 'en' | 'fr' | 'es' | 'ge',
  params: SayHelloParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sayHello>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof sayHello>>,
          TError,
          Awaited<ReturnType<typeof sayHello>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSayHello<
  TData = Awaited<ReturnType<typeof sayHello>>,
  TError = unknown,
>(
  languageCode: 'en' | 'fr' | 'es' | 'ge',
  params: SayHelloParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sayHello>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof sayHello>>,
          TError,
          Awaited<ReturnType<typeof sayHello>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSayHello<
  TData = Awaited<ReturnType<typeof sayHello>>,
  TError = unknown,
>(
  languageCode: 'en' | 'fr' | 'es' | 'ge',
  params: SayHelloParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sayHello>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useSayHello<
  TData = Awaited<ReturnType<typeof sayHello>>,
  TError = unknown,
>(
  languageCode: 'en' | 'fr' | 'es' | 'ge',
  params: SayHelloParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sayHello>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSayHelloQueryOptions(languageCode, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
