/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * User Service API
 * User Service API
 * OpenAPI spec version: 1.0.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { useQuery } from '@tanstack/react-query';

import { customFetch } from './custom-fetch';
export type SayHelloUser200 = {
  message: string;
};

export type GetUsers200Item = {
  id: string;
  name: string;
};

export type SayHelloParams = {
  /**
   * @minLength 1
   */
  name: string;
};

export type SayHello200 = {
  message: string;
};

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Says hello in multiple languages
 */
export const getSayHelloUserUrl = (languageCode: 'en' | 'fr' | 'es' | 'ge') => {
  return `http://localhost:3000/hello-user/${languageCode}`;
};

export const sayHelloUser = (
  languageCode: 'en' | 'fr' | 'es' | 'ge',
  options?: RequestInit
): Promise<SayHelloUser200> => {
  return customFetch<SayHelloUser200>(getSayHelloUserUrl(languageCode), {
    ...options,
    method: 'GET',
  });
};

export const getSayHelloUserQueryKey = (
  languageCode: 'en' | 'fr' | 'es' | 'ge'
) => {
  return [`http://localhost:3000/hello-user/${languageCode}`] as const;
};

export const getSayHelloUserQueryOptions = <
  TData = Awaited<ReturnType<typeof sayHelloUser>>,
  TError = unknown,
>(
  languageCode: 'en' | 'fr' | 'es' | 'ge',
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sayHelloUser>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSayHelloUserQueryKey(languageCode);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof sayHelloUser>>> = ({
    signal,
  }) => sayHelloUser(languageCode, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!languageCode,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof sayHelloUser>>,
    TError,
    TData
  > & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type SayHelloUserQueryResult = NonNullable<
  Awaited<ReturnType<typeof sayHelloUser>>
>;
export type SayHelloUserQueryError = unknown;

export function useSayHelloUser<
  TData = Awaited<ReturnType<typeof sayHelloUser>>,
  TError = unknown,
>(
  languageCode: 'en' | 'fr' | 'es' | 'ge',
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sayHelloUser>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof sayHelloUser>>,
          TError,
          Awaited<ReturnType<typeof sayHelloUser>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSayHelloUser<
  TData = Awaited<ReturnType<typeof sayHelloUser>>,
  TError = unknown,
>(
  languageCode: 'en' | 'fr' | 'es' | 'ge',
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sayHelloUser>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof sayHelloUser>>,
          TError,
          Awaited<ReturnType<typeof sayHelloUser>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSayHelloUser<
  TData = Awaited<ReturnType<typeof sayHelloUser>>,
  TError = unknown,
>(
  languageCode: 'en' | 'fr' | 'es' | 'ge',
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sayHelloUser>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useSayHelloUser<
  TData = Awaited<ReturnType<typeof sayHelloUser>>,
  TError = unknown,
>(
  languageCode: 'en' | 'fr' | 'es' | 'ge',
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sayHelloUser>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSayHelloUserQueryOptions(languageCode, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get users
 */
export const getGetUsersUrl = () => {
  return 'http://localhost:3000/users';
};

export const getUsers = (options?: RequestInit): Promise<GetUsers200Item[]> => {
  return customFetch<GetUsers200Item[]>(getGetUsersUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getGetUsersQueryKey = () => {
  return ['http://localhost:3000/users'] as const;
};

export const getGetUsersQueryOptions = <
  TData = Awaited<ReturnType<typeof getUsers>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUsersQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsers>>> = ({
    signal,
  }) => getUsers({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUsers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUsersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUsers>>
>;
export type GetUsersQueryError = unknown;

export function useGetUsers<
  TData = Awaited<ReturnType<typeof getUsers>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsers>>,
          TError,
          Awaited<ReturnType<typeof getUsers>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUsers<
  TData = Awaited<ReturnType<typeof getUsers>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsers>>,
          TError,
          Awaited<ReturnType<typeof getUsers>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUsers<
  TData = Awaited<ReturnType<typeof getUsers>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetUsers<
  TData = Awaited<ReturnType<typeof getUsers>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetUsersQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Says hello in 3 languages
 */
export const getSayHelloUrl = (
  languageCode: 'en' | 'fr' | 'es' | 'ge',
  params: SayHelloParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `http://localhost:3000/hello/${languageCode}?${stringifiedParams}`
    : `http://localhost:3000/hello/${languageCode}`;
};

export const sayHello = (
  languageCode: 'en' | 'fr' | 'es' | 'ge',
  params: SayHelloParams,
  options?: RequestInit
): Promise<SayHello200> => {
  return customFetch<SayHello200>(getSayHelloUrl(languageCode, params), {
    ...options,
    method: 'GET',
  });
};

export const getSayHelloQueryKey = (
  languageCode: 'en' | 'fr' | 'es' | 'ge',
  params: SayHelloParams
) => {
  return [
    `http://localhost:3000/hello/${languageCode}`,
    ...(params ? [params] : []),
  ] as const;
};

export const getSayHelloQueryOptions = <
  TData = Awaited<ReturnType<typeof sayHello>>,
  TError = unknown,
>(
  languageCode: 'en' | 'fr' | 'es' | 'ge',
  params: SayHelloParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sayHello>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSayHelloQueryKey(languageCode, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof sayHello>>> = ({
    signal,
  }) => sayHello(languageCode, params, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!languageCode,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof sayHello>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type SayHelloQueryResult = NonNullable<
  Awaited<ReturnType<typeof sayHello>>
>;
export type SayHelloQueryError = unknown;

export function useSayHello<
  TData = Awaited<ReturnType<typeof sayHello>>,
  TError = unknown,
>(
  languageCode: 'en' | 'fr' | 'es' | 'ge',
  params: SayHelloParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sayHello>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof sayHello>>,
          TError,
          Awaited<ReturnType<typeof sayHello>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSayHello<
  TData = Awaited<ReturnType<typeof sayHello>>,
  TError = unknown,
>(
  languageCode: 'en' | 'fr' | 'es' | 'ge',
  params: SayHelloParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sayHello>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof sayHello>>,
          TError,
          Awaited<ReturnType<typeof sayHello>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSayHello<
  TData = Awaited<ReturnType<typeof sayHello>>,
  TError = unknown,
>(
  languageCode: 'en' | 'fr' | 'es' | 'ge',
  params: SayHelloParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sayHello>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useSayHello<
  TData = Awaited<ReturnType<typeof sayHello>>,
  TError = unknown,
>(
  languageCode: 'en' | 'fr' | 'es' | 'ge',
  params: SayHelloParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sayHello>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSayHelloQueryOptions(languageCode, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
