/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface Migrations {
  name: string;
  timestamp: string;
}

export interface DB {
  migrations: Migrations;
}
